version: "3.9"
services:
  mysql:
    container_name: mysql
    build: ./api/mysql
    networks:
      - intern-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql_api:
    container_name: mysql_api
    build: .
    working_dir: /app/api/mysql_api
    command: node mysql_api.js
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - intern-network

  web_page:
    container_name: web_page
    build: .
    working_dir: /app/api/web_page
    command: node web.js
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql_api
    networks:
      - intern-network

  data_ingestion:
    container_name: data_ingestion
    build: .
    working_dir: /app/api/data_ingestion
    command: node ingestionData.js
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql_api
    networks:
      - intern-network
    
  data_craw:
    container_name: data_craw
    build: .
    working_dir: /app/api/data_craw
    command: node crawData.js
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - data_ingestion
    networks:
      - intern-network

  api_gateway:
    image: nginx:latest
    container_name: api_gateway
    volumes:
      - ./api/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - mysql_api
      - web_page
      - data_ingestion
      - data_craw
    networks:
      - intern-network


networks:
  intern-network:
    name: nhom999_network
    driver: bridge